# PATHS: change accordingly
data_directory: '/home/manuel_servex/audios/vanessa/' # path to wavs and metafile directory
log_directory: '/home/manuel_servex/train_20_02_2021/'   # weights and logs are stored here
train_data_directory: 'transformer_tts_data'         # optional: alternative directory where to store processed data (default is data_dir)
wav_subdir_name: 'wavs'            # subfolder in data_directory containing wavs files
metadata_filename: 'metadata.csv'  # name of metadata file under data_directory
session_name: 'servex'                 # session naming, can be specified in command line

# DATA
n_samples: 100000
n_test: 100
mel_start_value: 4
mel_end_value: -4

# AUDIO
sampling_rate: 22050
n_fft: 2048
mel_channels: 80
hop_length: 275
win_length: 1100
f_min: 40
f_max: null
normalizer: WaveRNN                 # which mel normalization to use from utils.audio.py
# TOKENIZER
phoneme_language: 'es-la'
